TOP=top
HDL?=verilog
CST=src/hdmi_oss.cst
SDC=src/hdmi_oss.sdc
VERILOG_INCLUDE_DIRS=src src/hdmi
VERILOG_SOURCES= \
	src/gowin_clkdiv/gowin_clkdiv.v \
	src/gowin_rpll/gowin_rpll.v \
	src/hdmi/svo_enc.v \
	src/hdmi/svo_openldi.v \
	src/hdmi/svo_tcard.v \
	src/hdmi/svo_term.v \
	src/hdmi/svo_tmds.v \
	src/hdmi/svo_utils.v \
	src/hdmi/svo_vdma.v \
	src/svo_hdmi.v \
	src/top.v

include ../mk/tangnano9k.mk
